language: python
sudo: required
services:
  - docker
env:
 global:
   - CONAN_UPLOAD: 1
   - CONAN_REFERENCE: "zlib/1.2.8"
   - CONAN_USERNAME: "lasote"
   - CONAN_CHANNEL: "ci"
   - CONAN_TOTAL_PAGES: 1
   - CONAN_CURRENT_PAGE: 1
   - CONAN_USE_DOCKER: 1
 matrix:
   - CONAN_GCC_VERSIONS: 4.6 
   - CONAN_GCC_VERSIONS: 4.8 
   - CONAN_GCC_VERSIONS: 4.9 
   - CONAN_GCC_VERSIONS: 5.2 
   - CONAN_GCC_VERSIONS: 5.3

install:
  - pip install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory
script:
  - python build.py
