env:
 global:
   - CONAN_UPLOAD: 1
   - CONAN_REFERENCE: "zlib/1.2.8"
   - CONAN_USERNAME: "lasote"
   - CONAN_CHANNEL: "ci"
   - CONAN_TOTAL_PAGES: 1
   - CONAN_CURRENT_PAGE: 1
matrix:
   include:
#        - os: linux
#          env:
#            - CONAN_GCC_VERSIONS: 4.6 
#            - CONAN_USE_DOCKER: 1
#          services:
#            - docker
#          sudo: required
#          language: python
#        - os: linux
#          env:
#            - CONAN_GCC_VERSIONS: 4.8 
#            - CONAN_USE_DOCKER: 1
#          services:
#            - docker
#          sudo: required
#          language: python
#        - os: linux
#          env:
#            - CONAN_GCC_VERSIONS: 4.9 
#            - CONAN_USE_DOCKER: 1
#          services:
#            - docker
#          sudo: required
#          language: python
#        - os: linux
#          env:
#            - CONAN_GCC_VERSIONS: 5.2 
#            - CONAN_USE_DOCKER: 1
#          services:
#            - docker
#          sudo: required
#          language: python
#        - os: linux
#          env:
#            - CONAN_GCC_VERSIONS: 5.3 
#            - CONAN_USE_DOCKER: 1
#          services:
#            - docker
#          sudo: required
#          language: python
       - os: osx 
         osx_image: xcode7.3 # apple-clang 7.0
         language: generic
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
       - os: osx 
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
